In [11]:
import numpy as np

arr = np.array(list([[1,2,3], [4,5,6],[7,8,9],[11,12,13]]))

In [13]:
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 12, 13]])

In [20]:
# will convert 4*3 array into 1D array
flat = arr.flatten()

In [22]:
flat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 11, 12, 13])

In [24]:
b = flat[3:7]

In [26]:
b

array([4, 5, 6, 7])

In [28]:
b[0] = 777

In [30]:
b

array([777,   5,   6,   7])

In [32]:
flat

array([  1,   2,   3, 777,   5,   6,   7,   8,   9,  11,  12,  13])

In [34]:
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [11, 12, 13]])

In [3]:
import numpy as np
arr1 = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [5]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
arr1.shape

(3, 3)

In [ ]:
arr = arr