In [4]:
import numpy as np

arr = np.array([[1, 2, 3], 
                [4, 5, 6], 
                [7, 8, 9]])

print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [6]:
np.sum(arr, axis=1)

array([ 6, 15, 24])

In [8]:
arr[0][2]

3

In [10]:
arr[0:2, 1:3]

array([[2, 3],
       [5, 6]])

In [12]:
# 3D array
arr3D = np.array([[[1, 2, 3], [4, 5, 6]],
                  [[7, 8, 9], [10, 11, 12]]])

In [14]:
print(arr3D[:,0,:])

[[1 2 3]
 [7 8 9]]


In [16]:
arr3D[:,0,:] = 0

In [18]:
arr3D

array([[[ 0,  0,  0],
        [ 4,  5,  6]],

       [[ 0,  0,  0],
        [10, 11, 12]]])